### ISSUE TITLE
ValueError: 'timestamp' is not in list

### ISSUE THREAD

**Issue by brett-am** [amberdata/jupyter-notebook#5]
Following the medium post out of the box results in a timestamp not in list. Seems to be an issue with the CSV header.

```
Traceback (most recent call last):
  File "~/amberAnalysis/analysis_arch.py", line 247, in <module>
    btc_stf = to_pandas(amberdata_stf("btc", start_date, end_date))
  File "~/amberAnalysis/analysis_arch.py", line 89, in to_pandas
    return pd.read_csv(io.StringIO(csv), index_col='timestamp', parse_dates=True)
  File "~/amberAnalysis/venv/lib/python3.8/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "~/amberAnalysis/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "~/amberAnalysis/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "~/amberAnalysis/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "~/amberAnalysis/venv/lib/python3.8/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "~/amberAnalysis/venv/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 157, in __init__
    self._set_noconvert_columns()
  File "~/amberAnalysis/venv/lib/python3.8/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 213, in _set_noconvert_columns
    noconvert_columns = self._set_noconvert_dtype_columns(
  File "~/amberAnalysis/venv/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 668, in _set_noconvert_dtype_columns
    noconvert_columns.add(_set(k))
  File "~/amberAnalysis/venv/lib/python3.8/site-packages/pandas/io/parsers/base_parser.py", line 645, in _set
    x = col_indices[names.index(x)]
ValueError: 'timestamp' is not in list

Process finished with exit code 1
```

**Comment by joanesespanol** [comment]
Hi @brett-am,
Can you give us a little bit more details as to which medium post your are referring to, and/or which code snippet is causing this issue?

**Comment by brett-am** [comment]
@joanesespanol Yes, apologies:
medium post:
https://medium.com/amberdata/backtesting-your-cryptocurrency-trading-strategy-for-fun-and-profits-with-the-amberdata-api-and-6ea912aae28e
Code: 
BTC_LO_MCD_SMA_STF_Perct_TS.py
